apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: test-app
spec:
  rules:
  - host: hello-world.com
    http:
      paths:
      - backend:
          serviceName: hello-kubernetes
          servicePort: 80