apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: test-app
  namespace: elastic-system
spec:
  rules:
  - host: kibana.chriscarty.com
    http:
      paths:
      - backend:
          serviceName: quickstart-kb-http
          servicePort: 5601